version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: wallet_postgres
    ports:
      - "6666:5432"
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    #    image: wallet:1.0 - если запускать из готового образа
    container_name: wallet_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
